### ISSUE TITLE
Issue with High Healer Half EXP Plugin

### ISSUE THREAD

**Issue by ArbanGarrera** [RogueClaris/SRPGStudioScripts#1]
Hi. I am experiencing an issue with the High Healer Half EXP Plugin. It appears to cause issues with Experience Up-type skills. I have a skill that doubles EXP (200%) One of my units is a healer with that skill. However, when she gains EXP from healing, the EXP is quadrupled instead. For reference, the staff she was using gives her 20 EXP per use. With the skill, she was supposed to get 40, but she got 80 instead. This bug doesn't occur with other types of weapons like swords and bows, it only happens with staves. I eventually figured out this plugin was the cause of this bug.

**Comment by RogueClaris** [comment]
Thank you for the report.

At first I did not believe this bug was present, as I have had trouble with SRPG Studio's default settings before - sometimes 100% means _adding_ 100% which doubles a gain, so I was wondering if it was that.

However, that was not the case; the issue was found. I have uploaded a repaired script, but please double check the following information to ensure it is all in place:

- The class of the healer is set to the High type in the database. This is on the right-most side of the Description text entry area, just above it. If it says "Low", click it to change it to "High", as this script only applies to High rank healers.
- Ensure the item is set to the Wand type. It may be marked as Staff in the engine. To check this, go to the item in your database and look at the Category box. If it says 'Item', you should change it.

Please let me know if you encounter any further issues.

**Comment by ArbanGarrera** [comment]
Hi. Thank you for responding to my issue. I tried the updated plugin and the bug is no longer present. The healer gains the correct EXP with the Experience Up skill equipped. 200% as it should be. Thanks again for helping me.

**Comment by RogueClaris** [comment]
> Hi. Thank you for responding to my issue. I tried the updated plugin and the bug is no longer present. The healer gains the correct EXP with the Experience Up skill equipped. 200% as it should be. Thanks again for helping me.

No problem at all, glad we could resolve it. I'm going to Close the issue now, but if anything comes up, don't hesitate to open another.
